title: "testing in progress"
description: "testing in progress"
theme: minima            # built-in GitHub Pages theme
url: "https://dermawan.net"
markdown: kramdown
permalink: /:categories/:title/
paginate: 5
paginate_path: "/page:num/"
